name: Fix Form (不具合報告; Form ver.)
description: Create a report to help us improve
title: "fix: <title>"
labels: ["bug"]
body:
- type: textarea
  attributes:
    label: Screenshots
    description: |
      If applicable, add screenshots to help explain your problem.
      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    render: markdown
  validations:
    required: false
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      1. With this config...
      1. Run '...'
      1. See error...
  validations:
    required: false
- type: textarea
  attributes:
    label: Environment
    description: |
      examples:
        - **Device**: iPhone 12 mini
        - **OS**: iOS 15.2.1
        - **Browser**: Safari
        - **Misc.**: Private mode
    value: |
        - Device:
        - OS:
        - Browser:
        - Misc.:
    render: markdown
  validations:
    required: false
- type: textarea
  attributes:
    label: Appendix
    description: |
      Links, references or anything that will give us more context about the issue you are encountering!
  validations:
    required: false
